# docker-compose.yml
services:
  wazuh-manager:
    build: ./wazuh
    image: custom-wazuh-manager
    environment:
      - API_USER=${WAZUH_API_USER}
      - API_PASS=${WAZUH_API_PASS}
    ports:
      - "1514:1514/udp"
      - "1515:1515/tcp"
      - "55000:55000/tcp"
    volumes:
      - wazuh-data:/var/ossec
    networks:
      - wazuh-net

  wazuh-indexer:
    image: wazuh/wazuh-indexer:4.7.2
    environment:
      - INDEXER_PASSWORD=${INDEXER_PASSWORD}
    ports:
      - "9200:9200"
    networks:
      - wazuh-net

  wazuh-dashboard:
    image: wazuh/wazuh-dashboard:4.7.2
    environment:
      - INDEXER_URL=https://wazuh-indexer:9200
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=${INDEXER_PASSWORD}
    ports:
      - "443:5601"
    depends_on:
      - wazuh-indexer
    networks:
      - wazuh-net

  bgp-detector:
    build: ./detectors/bgp-hijack
    environment:
      - WAZUH_API=http://wazuh-manager:55000
      - WAZUH_API_USER=${WAZUH_API_USER}
      - WAZUH_API_PASS=${WAZUH_API_PASS}
      - USE_MOCK=${USE_MOCK:-true}
      - CHECK_INTERVAL=300
    networks:
      - wazuh-net
    restart: unless-stopped

  ssh-detector:
    build: ./detectors/ssh-bruteforce
    environment:
      - WAZUH_API=http://wazuh-manager:55000/api/alert
      - WAZUH_API_USER=${WAZUH_API_USER}
      - WAZUH_API_PASS=${WAZUH_API_PASS}
      - USE_MOCK=${USE_MOCK:-true}
      - FAILED_ATTEMPT_THRESHOLD=5
      - TIME_WINDOW_MINUTES=10
    volumes:
      - /var/ossec/logs/alerts:/var/ossec/logs/alerts:ro
    networks:
      - wazuh-net
    restart: unless-stopped

networks:
  wazuh-net:
    driver: bridge

volumes:
  wazuh-data: